const examples = [
  {
    name: "Title",
    pointOne: "Point 1",
    pointTwo: "Point 2",
    gitLink: "https://github.com/otekolste",
    appLink: "https://github.com/otekolste",
    imgPath: "/src/assets/images/answerHive.png",
    imgAlt: "Screenshot",
    id: 1,
  },
  {
    name: "Title",
    pointOne: "Point 1",
    pointTwo: "Point 2",
    gitLink: "https://github.com/otekolste",
    appLink: "https://github.com/otekolste",
    imgPath: "/src/assets/images/answerHive.png",
    imgAlt: "Screenshot",
    id: 2,
  },
  {
    name: "Title",
    pointOne: "Point 1",
    pointTwo: "Point 2",
    gitLink: "https://github.com/otekolste",
    appLink: "https://github.com/otekolste",
    imgPath: "/src/assets/images/answerHive.png",
    imgAlt: "Screenshot",
    id: 3,
  },
  {
    name: "Title",
    pointOne: "Point 1",
    pointTwo: "Point 2",
    gitLink: "https://github.com/otekolste",
    appLink: "https://github.com/otekolste",
    imgPath: "/src/assets/images/answerHive.png",
    imgAlt: "Screenshot",
    id: 4,
  },
  {
    name: "Title",
    pointOne: "Point 1",
    pointTwo: "Point 2",
    gitLink: "https://github.com/otekolste",
    appLink: "https://github.com/otekolste",
    imgPath: "/src/assets/images/answerHive.png",
    imgAlt: "Screenshot",
    id: 5,
  },
  {
    name: "Title",
    pointOne: "Point 1",
    pointTwo: "Point 2",
    gitLink: "https://github.com/otekolste",
    appLink: "https://github.com/otekolste",
    imgPath: "/src/assets/images/answerHive.png",
    imgAlt: "Screenshot",
    id: 6,
  },
];

export default examples;
